[build]
  command = "make build"
  functions = "my_functions"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/rgehrsitz/makefieldmusic"  

[[redirects]]
  from = "/old-path/hello"
  to = "/.netlify/functions/hello"
  status = 301

  [[redirects]]
  from = "/old-path/hellogo"
  to = "/.netlify/functions/hellogo"
  status = 301